name: Check Server Location

# This tells GitHub to run the script manually whenever you want
on:
  workflow_dispatch:

jobs:
  check-ip:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Server Location Info
        run: curl ipinfo.io
